# Global env for steps
steps:
  # Terraform apply for deploy
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform plan -out=tfplan
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform apply tfplan
  # List revisions
  - id: 'list revisions'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - revisions
      - list
      - --region=$_REGION

  # script for traffic splits
  - id: 'traffic split'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        readarray -t REVISIONS < <(gcloud run revisions list --region=$_REGION --format="value(metadata.name)")

        echo "$${REVISIONS[0]}"
        echo "$${REVISIONS[1]}"
        echo "$${REVISIONS[2]}"
        echo "$${REVISIONS[3]}"

        gcloud run services update-traffic cloudrun-service \
          --to-revisions $${REVISIONS[0]}=40,$${REVISIONS[1]}=40,$${REVISIONS[2]}=10,$${REVISIONS[3]}=10 \
          --region $_REGION 

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TF_VAR_project_id=$PROJECT_ID'
    - 'TF_VAR_region=$_REGION'
